apiVersion : apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app : {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      project: {{ .Release.Name }}
  template:
    metadata:
      labels:
      containers:
        - name : {{ .Release.Name }}-web
          image: "{{ .Values.container.image}}:{{ .Values.container.tag}}"
          ports:
            - containerPort: 8080
